name: Bump version and Publish package workflow

on:
  push:
    branches:
    - master

jobs:
   
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: false

    - name: current_version
      run: echo "current_version=$(grep current_version .bumpversion.cfg | cut -d' ' -f3)" >> $GITHUB_ENV

    - name: FragileTech/bump-version
      uses: FragileTech/bump-version@main
      with:
        current_version: "${{ env.current_version }}"
        files: ".bumpversion.cfg setup.py reader/__init__.py reader/__main__.py"
        commit_name: tchia04-bot
        commit_email: tchia04@gmail.com
        login: tchia04
        token: "${{ secrets.MY_GITHUB_API_TOKEN }}"

  publish-package:
    name: Publish package to pypi
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    steps:
    - name: actions/checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: false

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build a new package with the new version number
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        # https://pypi.org/help/#invalid-auth
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
