
name: Node Continuous Integration

on:
  push:
  pull_request:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
      
jobs:
  node_12_test:
    #runs-on: self-hosted
    #runs-on: macos
    runs-on: x64
    #runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: node --version

  node_14_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: node --version

  node_16_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: node --version

  node_18_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: node --version
